=== Harsh-Sharma-0001/Adobe-India-Hackathon25/Challenge_1a/sample_dataset/schema/output_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "PDF Output Schema",
  "type": "object",
  "properties": {
    "filename": { "type": "string" },
    "content": { "type": "string" },
    "sections": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": { "type": "string" },
          "text": { "type": "string" }
        },
        "required": ["title", "text"]
      }
    },
    "tables": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "page": { "type": "integer" },
          "data": {
            "type": "array",
            "items": {
              "type": "array",
              "items": { "type": "string" }
            }
          }
        },
        "required": ["page", "data"]
      }
    },
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "page": { "type": "integer" },
          "image_file": { "type": "string" }
        },
        "required": ["page", "image_file"]
      }
    }
  },
  "required": ["filename", "content", "sections", "tables", "images"]
}

=== Harsh-Sharma-0001/Adobe-India-Hackathon25/Challenge_1a/sample_dataset/outputs/file05.json
{
  "filename": "file05.pdf",
  "content": "ADDRESS: \nTOPJUMP \n3735 PARKWAY \nPIGEON FORGE, TN 37863 \n(NEAR DIXIE STAMPEDE ON THE PARKWAY) \nRSVP: ----------------\nCLOSED TOED SHOES ARE REQUIRED FOR CLIMBING \nPARENTS OR GUARDIANS NOT ATTENDING THE PARTY, \nPLEASE VISIT TOPJUMP.COM TO FILL OUT WAIVER \nSO YOUR CHILD CAN ATTEND. \nHOPE To SEE You THERE! \nWWW.TOPJUMP.COM ",
  "sections": [
    {
      "title": "Introduction",
      "text": "ADDRESS: \n"
    },
    {
      "title": "TOPJUMP",
      "text": "3735 PARKWAY \nPIGEON FORGE, TN 37863 \n(NEAR DIXIE STAMPEDE ON THE PARKWAY) \nRSVP: ----------------\n"
    },
    {
      "title": "CLOSED TOED SHOES ARE REQUIRED FOR CLIMBING",
      "text": "PARENTS OR GUARDIANS NOT ATTENDING THE PARTY, \nPLEASE VISIT TOPJUMP.COM TO FILL OUT WAIVER \nSO YOUR CHILD CAN ATTEND. \nHOPE To SEE You THERE! \nWWW.TOPJUMP.COM \n"
    }
  ],
  "tables": [],
  "images": [
    {
      "page": 1,
      "image_file": "images/page1_img1.jpeg"
    },
    {
      "page": 1,
      "image_file": "images/page1_img2.png"
    }
  ]
}
